import Head from 'next/head'

import ProfileModule from '@/components/modules/Profile'
import TopNav from '@/components/modules/TopNav'
import Experience from '@/components/modules/Experience'
import Projects from '@/components/modules/Projects'

export default function Home() {
  return (
    <>
      <Head>
        <title>Oli Gray</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNav />
        <ProfileModule />

        

      </main>

    </>
  )
}
