import Head from 'next/head'

import ProfileModule from '@/components/modules/Profile'
import TopNav from '@/components/modules/TopNav'
import Experience from '@/components/modules/Experience'
import Projects from '@/components/modules/Projects'

export default function Home() {
  return (
    <>
      <Head>
        <title>Oli Gray</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNav />
        <div className='flex flex-row'>
          <div className="m-auto p-10">
              <div>👋 Hello, my name is</div>
              <div className="text-3xl">Oli Gray</div>
              <div className="text-xl">Software Developer and Cyber Criminal</div>

              <p className='text-left mt-3'>
                  bio for about me and what kinda stuff i be doing
                  and there is some cool stuff. hacking, reverse engineering,
                  software development, and more!
              </p>

              <div className="text-center">
                  have cool image here
              </div>
          </div>
        </div>

        

      </main>

    </>
  )
}
